# Generated by Django 5.2.6 on 2025-09-11 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('file_save', '文件保存'), ('file_convert', '文件转换'), ('file_upload', '文件上传'), ('file_download', '文件下载'), ('history_query', '历史查询'), ('statistics', '统计分析'), ('data_export', '数据导出')], max_length=100, verbose_name='操作类型')),
                ('response_time_ms', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='响应时间(毫秒)')),
                ('success', models.BooleanField(verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '性能统计',
                'verbose_name_plural': '性能统计',
                'db_table': 'performance_stats',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type', 'created_at'], name='performance_operati_fae759_idx'), models.Index(fields=['success', 'created_at'], name='performance_success_f06dc0_idx'), models.Index(fields=['response_time_ms'], name='performance_respons_52c1a5_idx')],
            },
        ),
    ]
