# Generated by Django 5.2.6 on 2025-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('original_path', models.TextField(blank=True, null=True, verbose_name='原始路径')),
                ('final_path', models.TextField(verbose_name='最终保存路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('file_extension', models.CharField(blank=True, max_length=20, verbose_name='文件扩展名')),
                ('content_preview', models.TextField(blank=True, verbose_name='内容预览')),
                ('save_mode', models.CharField(default='manual', max_length=50, verbose_name='保存模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件保存历史',
                'verbose_name_plural': '文件保存历史',
                'db_table': 'save_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
