# Generated by Django 5.2.6 on 2025-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.TextField(verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_extension', models.CharField(blank=True, max_length=20, verbose_name='文件扩展名')),
                ('content_type', models.CharField(max_length=100, verbose_name='内容类型')),
                ('content_data', models.TextField(verbose_name='文件内容(base64编码)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件保存记录',
                'verbose_name_plural': '文件保存记录',
                'db_table': 'file_saves',
                'ordering': ['-created_at'],
            },
        ),
    ]
