# Generated by Django 5.2.6 on 2025-09-12 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_pattern', models.CharField(max_length=500, unique=True, verbose_name='路径模式')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('category', models.CharField(choices=[('default', '默认'), ('user_defined', '用户定义'), ('auto_generated', '自动生成'), ('recommended', '推荐'), ('frequent', '常用')], default='user_defined', max_length=20, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件路径',
                'verbose_name_plural': '文件路径',
                'db_table': 'file_paths',
                'ordering': ['-usage_count', '-last_used_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='filesave',
            name='file_path_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_save.filepath', verbose_name='关联路径'),
        ),
    ]
