# Generated by Django 5.2.6 on 2025-01-14 12:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_save', '0002_filepath_filesave_file_path_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesave',
            name='is_indexed',
            field=models.BooleanField(default=False, verbose_name='是否已索引'),
        ),
    ]
