# Generated by Django 5.2.6 on 2025-01-14 12:30:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_save', '0003_add_is_indexed_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('final_path', models.TextField(verbose_name='最终保存路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_extension', models.CharField(blank=True, max_length=20, verbose_name='文件扩展名')),
                ('content_preview', models.TextField(blank=True, verbose_name='内容预览')),
                ('save_mode', models.CharField(choices=[('normal', '普通保存'), ('append_to_similar', '追加到相似文件'), ('smart_save', '智能保存')], default='normal', max_length=20, verbose_name='保存模式')),
                ('source_url', models.URLField(blank=True, verbose_name='来源URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件保存历史',
                'verbose_name_plural': '文件保存历史',
                'db_table': 'file_save_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
